#ifndef BACKENDCLIENT_GLOBAL_H
#define BACKENDCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BACKENDCLIENT_LIBRARY)
#  define BACKENDCLIENT_EXPORT Q_DECL_EXPORT
#else
#  define BACKENDCLIENT_EXPORT Q_DECL_IMPORT
#endif

#endif // BACKENDCLIENT_GLOBAL_H
